config/routes.rb
Rails.application.routes.draw do
  root "budgets#index"
  resources :budgets do
    resources :categories
  end

  resources :monthly_assignments, only: [:index, :update, :show, :create]

  get "/movements/new", to: "movements#new"
  post "/movements", to: "movements#create"

  resources :accounts do
    post "sync", to: "accounts#sync"

    resources :movements
    resources :auth_sessions, only: [:create] do
      get "result", to: "auth_sessions#result"
    end
  end
end

app/models/budget.rb
class Budget < ApplicationRecord
  validates :title, presence: true
  has_many :categories, -> { order("name") }, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :movements, -> { includes(:account) }, through: :accounts
  after_create :create_ready_to_assign_category!

  def uncategorized_movements_in(current_month)
    beginning_of_month = current_month.beginning_of_month
    end_of_month = current_month.end_of_month
    movements.between_dates(beginning_of_month, end_of_month)
      .where(category_id: nil, transfer_to_account_id: nil)
  end

  def ready_to_assign
    ready_to_assign_cents = Category.find(ready_to_assign_category_id).spent_amount_cents * -1
    assigned_cents_in_categories = categories
      .joins(:monthly_assignments)
      .where
      .not(id: ready_to_assign_category_id)
      .sum("monthly_assignments.amount_cents")
    Money.new(ready_to_assign_cents - assigned_cents_in_categories, ready_to_assign_currency)
  end

  def needs_reconciliation?
    accounts.any? do |a|
      a.reported_balance != a.balance
    end
  end

  private

  def create_ready_to_assign_category!
    ready_to_assign_category = Category.create(budget_id: id, name: "Ready to Assign")
    update!(ready_to_assign_category_id: ready_to_assign_category.id)
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_selected_date, only: %i[show]
  before_action :set_budget, only: %i[show edit update destroy]

  # GET /budgets or /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_selected_date
    requested_month = params.dig(:date, :month)
    requested_year = params.dig(:date, :year)
    @current_month = (requested_month && requested_year) ? Date.new(params[:date][:year].to_i, params[:date][:month].to_i, 1) : Date.today.beginning_of_month
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_budget
    @budget = Budget
      .includes(:categories, :accounts, :movements)
      .find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def budget_params
    params.require(:budget).permit(:title)
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
  <p>
    <strong>Budget Name:</strong>
    <%= budget.title %>
  </p>

</div>

app/views/budgets/_card.html.erb
    <!-- Dropdown menu -->
<div id="<%= dom_id budget %> "class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow  ">
  <div class="flex justify-end px-4 pt-4">
    <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500  hover:bg-gray-100  focus:ring-4 focus:outline-none focus:ring-gray-200  rounded-lg text-sm p-1.5" type="button">
      <span class="sr-only">Open dropdown</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
    </button>
    <!-- Dropdown menu -->
  </div>
  <div class="flex flex-col items-center pb-10">
    <h5 class="mb-1 text-xl font-medium text-gray-900 ">
      <%= budget.title %>
    </h5>
    <div class="flex mt-4 space-x-3 md:mt-6">
      <%= link_to "Show budget", budget_path(budget), class: "inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200      " %>
    </div>
  </div>
</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>
      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>
<%= render "form", budget: @budget %>
<br>
<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex items-center justify-between mb-8">
  <h1 class="main-title">
    Budgets
  </h1>
  <%= link_to "New budget", new_budget_path, class: "btn-primary" %>
</div>
<div id="budgets" class="grid grid-cols-2 grid-rows-2 gap-5">
  <% @budgets.each do |budget| %>
    <%= render  partial: "card", locals: { budget: budget }  %>
  <% end %>
</div>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex items-center justify-between mb-5">
  <h1 class="main-title"><%= @budget.title %></h1>
  <% if @budget.needs_reconciliation?%>
  <div id="alert-1" class="flex p-4 max-w-lg rounded-lg bg-amber-50 text-amber-700 items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
      <path fill-rule="evenodd" d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 01.75.75v3.75a.75.75 0 01-1.5 0V9a.75.75 0 01.75-.75zm0 8.25a.75.75 0 100-1.5.75.75 0 000 1.5z" clip-rule="evenodd" />
    </svg>
    <span class="sr-only">Info</span>
    <p class="ml-3 text-sm font-medium" data-testid=>
      There's a mismatch in your any of the 
      <span> <%= link_to "budget's accounts.", accounts_path, class: 'underline hover:text-amber-800' %></span>
      You may need to reconcile it.
    </p>
  </div>
  <% end %>
  <div class="flex items-center justify-around">
    <%= link_to "Create movement", movements_new_path({ movement: { created_at: @current_month }}), class: "btn-primary" %>
    <%= link_to "Edit this budget", edit_budget_path(@budget), class: "btn-primary ml-3" %>
  </div>
</div>
<div class="grid grid-cols-2 gap-4">
  <section class="p-2">
    <div class="flex items-center justify-start mb-2 flex-nowrap">
      <% if @budget.ready_to_assign.cents > 0 %>
        <div id="alert-1" class="flex flex-1 p-4 mb-4 text-blue-800 rounded-lg bg-blue-50  min-w-[60%]" role="alert">
          <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Info</span>
          <div class="ml-3 text-sm font-medium">
            There are movements ready to budget <span class="font-semibold underline hover:no-underline">
              <%= humanized_money_with_symbol @budget.ready_to_assign %>
            </span>
          </div>
        </div>
      <% elsif  @budget.ready_to_assign.cents < 0 %>
        <div id="alert-2" class="flex p-4 mb-4 text-red-800 rounded-lg bg-red-50 flex-1 min-w-[60%]" role="alert">
          <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Info</span>
          <div class="ml-3 text-sm font-medium">
            Your budget is overspent.  <span class="font-semibold underline hover:no-underline">
              <%= humanized_money_with_symbol @budget.ready_to_assign %>
            </span>
          </div>
        </div>
      <% end %>
      <%= form_with url: "#{budget_url(@budget)}", class: 'ml-2 first:ml-0', method: :get do |form| %>
        <%= select_month(@current_month, {},
                         {
                           field_name: 'month',
                           onchange: 'this.form.requestSubmit()',
                           class: 'rounded-md border-0 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 mb-5 '
                         }) %>
        <%= select_year(@current_month, {},
                         {
                           field_name: 'year',
                           onchange: 'this.form.requestSubmit()',
                           class: 'rounded-md border-0 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 mb-5 ',
                           start_year: 2022
                         }) %>
      <% end %>
    </div>
    <div class="flex items-center mb-2">
      <h3 class="subtitle flex-1 min-w-[70%]">Categories</h3>
      <h5 class="grow-0 min-w-[15%] text-right">Assigned</h3>
      <h5 class="grow-0 min-w-[15%] text-right max-w-">Available to spend</h3>
    </div>
    <% @budget.categories.each do |category| %>
      <% if category.id != @budget.ready_to_assign_category_id %>
        <%= render category, locals: { current_month: @current_month } %>
      <% end %>
    <% end %>
    <div class="flex justify-start mt-4 gap-2">
      <%= link_to "Create category", new_budget_category_path(@budget), class: "btn-primary" %>
    </div>
  </section>
  <section>
    <h3 class="mb-5 subtitle">Uncategorized movements</h3>
    <div class="relative overflow-x-auto">
      <table class="w-full text-sm text-left text-gray-500 ">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50  ">
          <tr>
            <th scope="col" class="px-6 py-3">
              Description
            </th>
            <th scope="col" class="px-6 py-3">
              Amount
            </th>
            <th scope="col" class="px-6 py-3">
              Category
            </th>
            <th scope="col" class="px-6 py-3">
              Account
            </th>
            <th scope="col" class="px-6 py-3">
              Transfer to
            </th>
            <th scope="col" class="px-6 py-3">
              Date
            </th>
          </tr>
        </thead>
        <tbody>
          <% @budget.uncategorized_movements_in(@current_month).each do |movement| %>
            <tr class="bg-white border-b  ">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-normal ">
                <%= movement.description %>
              </th>
              <td class="px-6 py-4">
                <%= humanized_money_with_symbol movement.amount %>
              </td>
              <td class="px-6 py-4">
                <%= form_for [movement.account, movement] do |f| %>
                  <%= f.collection_select(:category_id, @budget.categories, :id, :name, { prompt: true }, { onchange: "this.form.requestSubmit()"}) %>
                  <%= f.hidden_field(:date, { value: @current_month}) %>
                <% end %>
              </td>
              <td class="px-6 py-4">
                <%= movement.account.name %>
              </td>
              <td class="px-6 py-4">
                <%= form_for [movement.account, movement] do |f| %>
                  <%= f.collection_select(:transfer_to_account_id, @budget.accounts, :id, :name, {prompt: true }, { onchange: 'this.form.requestSubmit()' }) %>
                  <%= f.hidden_field(:date, { value: @current_month}) %>
                <% end %>
              </td>
              <td class="px-6 py-4">
                <%= time_tag movement.created_at %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
</div>