config/routes.rb
Rails.application.routes.draw do
  root "budgets#index"
  resources :budgets do
    resources :categories
  end

  resources :monthly_assignments, only: [:index, :update, :show, :create]

  get "/movements/new", to: "movements#new"
  post "/movements", to: "movements#create"

  resources :accounts do
    post "sync", to: "accounts#sync"

    resources :movements
    resources :auth_sessions, only: [:create] do
      get "result", to: "auth_sessions#result"
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :institution
  belongs_to :budget
  has_many :movements, dependent: :destroy
  has_many :auth_sessions, -> { order(created_at: :desc) }, dependent: :destroy
  monetize :reported_balance_cents

  # https://developer.gocardless.com/bank-account-data/statuses
  AUTHENTICATED_STATUS = "LN".freeze

  def authenticated?
    return false unless external_account_id.present?

    requisition_id = auth_sessions&.first&.external_id
    return false unless requisition_id.present?

    requisition = OpenBankingConnector.new.fetch_requisition(requisition_id)

    requisition[:status] == AUTHENTICATED_STATUS
  end

  def balance
    Money.new(movements.sum(:amount_cents), "EUR")
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  def sync
    PullAccountMovementsJob.perform_later(account_id: params[:account_id])
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:name, :institution_id, :budget_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_card.html.erb
    <!-- Dropdown menu -->
<div id="<%= dom_id account %> "class="p-4 w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow  ">
  
<% if (account.reported_balance.cents.abs - account.balance.cents.abs) != 0 %>
 <div id="alert-additional-content-4" class="p-4 mb-4 text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50   " role="alert">
  <div class="flex items-center">
    <svg class="flex-shrink-0 w-4 h-4 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <h3 class="text-lg font-medium">There's a balances mismatch</h3>
  </div>
  <p class="mt-2 mb-4 text-sm">Your account needs to be reconcile to match the reported balance and the computed balance.</p>
  <p class="mt-2 mb-4 text-sm">Reported balance: <%= humanized_money_with_symbol account.reported_balance %></p>
  <p class="mt-2 mb-4 text-sm">Compute balance: <%= humanized_money_with_symbol account.balance %></p>
  <div class="flex justify-end">
    <%= link_to "Reconcile", movements_new_path({ movement: { created_at: @current_month, account_id: account.id, amount: Money.new(account.reported_balance.cents - account.balance.cents, "EUR"), description: 'Renconciliation movement', payer: 'Reconciliation movement' }}), class: "text-white bg-yellow-800 hover:bg-yellow-900 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-xs px-3 py-1.5 mr-2 text-center inline-flex items-center    " %>
  </div>
 </div>
<% end %>

 <div class="flex justify-end px-4 pt-4">
    <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500  hover:bg-gray-100  focus:ring-4 focus:outline-none focus:ring-gray-200  rounded-lg text-sm p-1.5" type="button">
      <span class="sr-only">Open dropdown</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
    </button>
    <!-- Dropdown menu -->
  </div>
  <div class="flex flex-col items-center pb-10">
    <%= image_tag(account.institution.thumbnail_url, class: "w-24 h-24 mb-3 rounded-full shadow-lg", skip_pipeline: true) %>
    <h5 class="mb-1 text-xl font-medium text-gray-900 ">
      <%= account.name %>
    </h5>
    <span class="text-sm text-gray-500 ">
      <%= account.balance || 0 %> €
    </span>
    <div class="flex mt-4 space-x-3 md:mt-6">
      <% if !account.authenticated? %>
        <%= button_to "Authenticate", account_auth_sessions_path(account), data: { turbo: false } %>
      <% else %>
        <%= button_to "Sync movements", account_sync_path(account), form_class: "btn-primary" %>
      <% end %>
      <%= link_to "Show Account", account_path(account), class: "inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200      " %>
    </div>
  </div>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :budget, style: "display: block"%>
    <%= form.collection_select(:budget_id, Budget.all ,:id, :title, prompt: true) %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :institution, style: "display: block"%>
    <%= form.collection_select(:institution_id, Institution.all ,:id, :name, prompt: true) %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/_movements_list.html.erb
<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left text-gray-500 ">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50  ">
      <tr>
        <th scope="col" class="px-6 py-3">
          Description
        </th>
        <th scope="col" class="px-6 py-3">
          Type
        </th>
        <th scope="col" class="px-6 py-3">
          Amount
        </th>
        <th scope="col" class="px-6 py-3">
          Category
        </th>
        <th scope="col" class="px-6 py-3">
          Transfer to/from
        </th>
        <th scope="col" class="px-6 py-3">
          Transfer account
        </th>
        <th scope="col" class="px-6 py-3">
          Date
        </th>
      </tr>
    </thead>
    <tbody>
      <% movements.each do |movement| %>
        <tr class="bg-white border-b  ">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-normal ">
            <%= movement.description %>
          </th>
          <td class="px-6 py-4">
            <%= movement.debit? ? "Debit" : "Credit" %>
          </td>
          <td class="px-6 py-4">
            <%= humanized_money_with_symbol movement.amount %>
          </td>
            <td class="px-6 py-4">
              <%= form_for [@account, movement] do |f| %>
                <%= f.collection_select(:category_id, Category.all, :id, :name,  { prompt: true }, { onchange: 'this.form.requestSubmit()' }) %>
              <% end %>
            </td>
            <td class="px-6 py-4">
            <% if !movement.transfer_to_account_id.nil? && movement.transfer_to_account_id != @account.id %>
              <p>
              <span class="text-2xl"/>➡️</span> Outflow
              </p>
            <% elsif !movement.transfer_to_account_id.nil? %>
              ⬅️ Inflow
            <% end %>
            </td>
            <td class="flex items-center justify-between px-6 py-4">
              <%= form_for [@account, movement] do |f| %>
                <%= f.collection_select(:transfer_to_account_id, Account.where.not(id: @account.id), :id, :name, { include_blank: true }, { onchange: 'this.form.requestSubmit()' }) %>
              <% end %>
              <% if !movement.transfer_to_account_id.nil? && movement.transfer_to_account_id != @account.id %>
                <%= link_to "See account", account_path(movement.transfer_to_account_id) %> 
              <% end %>
            </td>
            <td class="px-6 py-4">
              <%= time_tag movement.created_at %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex items-center justify-between mb-8">
  <h1 class="main-title">
    Accounts
  </h1>
  <%= link_to "New account", new_account_path, class: "btn-primary" %>
</div>
<div id="accounts" class="grid grid-cols-2 grid-rows-2 gap-5">
  <% @accounts.each do |account| %>
    <div class="mb-5">
      <%= render  partial: "card", locals: { account: account }  %>
    </div>
  <% end %>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<h1 class="mb-5 main-title">Account: <%= @account.name %></h1>
<p style="color: green"><%= notice %></p>
<h2 class="mb-5 subtitle">Movements</h2>
<%= render partial: "movements_list", locals: { movements: @account.movements.order(created_at: :desc), account: @account } %>
<div class="flex justify-start gap-2 mt-4">
  <%= link_to "Edit this account", edit_account_path(@account), class: "btn-primary" %>
  <%= link_to "Back to accounts", accounts_path, class: "btn-primary" %>
  <%= button_to "Destroy this account", @account, method: :delete, class: "btn-primary bg-red-600" %>
</div>